node("docker") {
    docker.withRegistry('DockerJenkins', 'samprati18') {
    
        git url: "https://github.com/samprati18/DockerJenkins.git", credentialsId: 'samprati18'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
    
        stage "build"
        def app = docker.build "spring-eureka-server"
    
        stage "publish"
        app.push 'develop'
        app.push "${commit_id}"
    }
}