node {
 
    withMaven(maven:'maven') {
 
        stage('Checkout') {
            git url: 'https://github.com/samprati18/DockerJenkins.git', credentialsId: 'samprati18', branch: 'develop'
        }
 
        stage('Build') {
            sh 'mvn clean install'
 
            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }
 
        stage('Image') {
            dir ('discovery-service') {
                def app = docker.build "discovery-service:${env.version}"
                app.push()
            }
        }
 
        stage ('Run') {
            docker.image("discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }
      
 
    }
 
}